/*
 Copyright (c) 2012 GFT Appverse, S.L., Sociedad Unipersonal.

 This Source Code Form is subject to the terms of the Appverse Public License 
 Version 2.0 (“APL v2.0�?). If a copy of the APL was not distributed with this 
 file, You can obtain one at http://www.appverse.mobi/licenses/apl_v2.0.pdf. [^]

 Redistribution and use in source and binary forms, with or without modification, 
 are permitted provided that the conditions of the AppVerse Public License v2.0 
 are met.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. EXCEPT IN CASE OF WILLFUL MISCONDUCT OR GROSS NEGLIGENCE, IN NO EVENT
 SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT(INCLUDING NEGLIGENCE OR OTHERWISE) 
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
 POSSIBILITY OF SUCH DAMAGE.
 */
package org.appverse.web.framework.backend.security.xs.xss;

import static org.hamcrest.Matchers.*;
import static org.junit.Assert.assertThat;

import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.Proxy.Type;

import org.appverse.web.framework.backend.frontfacade.rest.authentication.basic.services.BasicAuthenticationService;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext;
import org.springframework.boot.context.embedded.FilterRegistrationBean;
import org.springframework.boot.test.OutputCapture;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.boot.test.TestRestTemplate;
import org.springframework.boot.test.WebIntegrationTest;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.security.crypto.codec.Base64;
import org.springframework.stereotype.Controller;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;

/**
 * IMPORTANT: If you use an authentication method that relies on JSESSIONID, you need to set the Spring Boot property
 * that controls http session creation strategy as:
 * security.sessions=NEVER
 * This mean that Spring will never create an HttpSession proactively but if it exists it will use it.
 * Spring default value is 'STATELESS' which means that Spring will never create an HttpSession proactively and it will
 * never use it.
 * This test uses Appverse Web {@link BasicAuthenticationService} for basic authentication and for XSRF token creation.
 * It relies on JSESSIONID so we have added the property to application.properties.
 * Take into account that if you use external generation for the XSRF token (is not generated by the own filter) you need
 * to exclude the URI that generates the XSRF token, in this case we have added the property:
 * appverse.security.xs.xsrffilter.exclude=/api/sec/login
 * 
 * Necessary to have httpclient for this tests (with scope tests) so that the http returns are handle correctly.
 * Otherwise you will experience exactly the problem described here:
 * http://stackoverflow.com/questions/27341604/exception-when-using-testresttemplate 
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration
@WebIntegrationTest(randomPort= true, 
					value={"security.basic.enabled=false",
						   "security.sessions=NEVER",
						   "appverse.security.xs.xsrf.filter.enabled=false"})
public class XssFilterTests {
	
	@Autowired
	private AnnotationConfigEmbeddedWebApplicationContext context;
	
	@Rule
	public OutputCapture capture = new OutputCapture();	
	
	// Be Careful!!! TestRestTemplate ignores cookies
	RestTemplate restTemplate = new RestTemplate();	
	
	@Configuration
	@EnableAutoConfiguration
	@RestController
	//@Controller
	public static class ApplicationTest {

		public static void main(String[] args) {
			SpringApplication.run(ApplicationTest.class, args);
		}

		@RequestMapping(value="/test", method = RequestMethod.POST)
		public void test(@RequestHeader("testHeader") String testHeader,
				         @RequestBody String requestBody){
			System.out.println(testHeader);
			System.out.println(requestBody);			
		}
		
		@RequestMapping(value="/test/{var}", method = RequestMethod.GET)
		public String test2(@RequestHeader("testHeader") String testHeader,
				          @PathVariable String var){
			System.out.println(testHeader);
			System.out.println(var);
			return "";
		}
	}
	
	
	
	@Test
	public void testInitParameterConfiguration() {
		FilterRegistrationBean registrationBean = this.context.getBean("xssFilter",
				FilterRegistrationBean.class);
		assertThat(registrationBean.getInitParameters().size(), equalTo(3));
		assertThat(registrationBean.getInitParameters().get("urlPattern"),
				equalTo("/*"));		
		assertThat(registrationBean.getInitParameters().get("match"),
				equalTo("*"));
		assertThat(registrationBean.getInitParameters().get("wildcards"),
				equalTo("false"));
		assertThat(registrationBean.getInitParameters().get("exclude"),
				equalTo(null));
	}
	
	
	/*
	 * Enable this init method if you need to use a proxy to debug (fiddler, for instance)
	 * This is required as passing regular JVM arguments for proxy setup seems not to work with RestTemplate
	 * as it uses Apache HttpClient
	 */ 
    @Before
    public void initProxy(){    	
		SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
	    Proxy proxy= new Proxy(Type.HTTP, new InetSocketAddress("localhost", 8888));
	    requestFactory.setProxy(proxy);
	    restTemplate = new RestTemplate(requestFactory);    	
    }
	
	@Test
	public void testXssFilterPost() throws Exception{
		HttpHeaders headers = new HttpHeaders();
		headers.set("testHeader", "add here xss");
		HttpEntity<String> entity = new HttpEntity<String>("testParamInBody1=testvalue1", headers);
		
		int port = context.getEmbeddedServletContainer().getPort();
		ResponseEntity<String> entityResult = restTemplate.postForEntity("http://localhost:" + port + "/test", entity, String.class);		
		assertThat(capture.toString(), containsString("add here xss"));
		assertThat(capture.toString(), containsString("testParamInBody1=testvalue1"));
	}
	
	@Test
	public void testXssFilterGet() throws Exception{
		HttpHeaders headers = new HttpHeaders();
		headers.set("testHeader", "add here xss");
		HttpEntity<String> entity = new HttpEntity<String>(headers);
		
		int port = context.getEmbeddedServletContainer().getPort();
		restTemplate.exchange("http://localhost:" + port + "/test/blabla", HttpMethod.GET, entity, String.class);
		//ResponseEntity<String> entityResult = restTemplate.getForEntity("http://localhost:" + port + "/test/blabla", String.class, entity);		
		assertThat(capture.toString(), containsString("add here xss"));
		assertThat(capture.toString(), containsString("blabla"));
	}
}
